name: Akasztófa játék
description: Szókitalálós játék, ahol betűnként tippelünk, a helyes betűk felfedésre kerülnek, rossz tippeléskor viszont az akasztófa épül. Vigyázz, hogy azelőtt kitaláld a szót, mielőtt befejeződne az akasztás!
