const HungarianSettlements = [
  "Balassagyarmat",
  "Balatonalmádi",
  "Balatonfüred",
  "Balatonfűzfő",
  "Balatonkenese",
  "Balkány",
  "Balmazújváros",
  "Budapest",
  "Debrecen",
  "Dunaföldvár",
  "Dunaharaszti",
  "Dunakeszi",
  "Dunaújváros",
  "Dunavarsány",
  "Dunavecse",
  "Érd",
  "Fehérgyermat",
  "Győr",
  "Kecskemét",
  "Miskolc",
  "Nyíregyháza",
  "Újfehértó",
  "Pécs",
  "Szeged",
  "Székesfehérvár",
  "Szolnok",
  "Szombathely"
];

const GermanSettlements = [
  "Bergish Gladbach",
  "Berlin",
  "Bremen",
  "Dresden",
  "Essen",
  "Frankfurt am Main",
  "Hamburg",
  "Heidelberg",
  "Köln",
  "Ludwigshafen am Rhein",
  "Lutherstadt Wittenberg",
  "Mainz",
  "Mönchengladbach",
  "München",
  "Nürnberg",
  "Offenbach am Main",
  "Potsdam",
  "Stuttgart",
  "Düsseldorf",
  "Drortmund",
  "Essen",
  "Leipzig",
  "Hannover",
  "Duisburg",
  "Augsburg",
  "Magdeburg",
  "Oldenburg",
  "Regensburg"
];
